### ISSUE TITLE
Notes "C D E F G A B C" in addition to integers?

### ISSUE THREAD

**Issue by kpanic** [pcorey/chord#5]
Hey @pcorey ,
I would like to try to add support for notes in string format.

For example:

```elixir
iex(2)> Chord.voicings(["C", "E", "G", "B"]) |> List.first() |> Chord.to_string() |> IO.puts()
 0 ●┬┬●┬┬ 
   ├┼┼┼┼┤
   ││││●│
   ├┼┼┼┼┤
   │●││││
   ├┼┼┼┼┤
   ││││││
         
:ok
```

I have no musical training at the moment :wink:, however how does this sounds?

Thanks!

**Comment by pcorey** [comment]
Sounds good to me. Feel free to take a crack at it! One suggestion though, be sure to include sharps and flats along with the natural notes. Some of these will overlap since they're "enharmonic equivalents".

C -> 0
C# -> 1
Db -> 1
D -> 2
etc...
